fos_rest:
  view:
    view_response_listener:  true
  format_listener:
    rules:
      - { path: '^/api', priorities: ['json', 'html'], fallback_format: html, prefer_extension: true }
      - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }